version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5174:5174"
    networks:
      - flaschenpost-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # nginx listens on port 80, mapped to 8080 on host
    depends_on:
      - backend
    networks:
      - flaschenpost-net

networks:
  flaschenpost-net:
    driver: bridge
