version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    networks:
      - flaschenpost-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  flaschenpost-net:
    driver: bridge
